### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by e1Ru1o** [2kodevs/matcom_scheduler#26]

**Comment by AntiD2ta** [comment]
[wiki][EN] Initial [home](https://github.com/2kodevs/matcom_scheduler/wiki) page created

**Comment by AntiD2ta** [comment]
[wiki] Footer added

**Comment by AntiD2ta** [comment]
[wiki][ES] Initial [home](https://github.com/2kodevs/matcom_scheduler/wiki/Home_ES) page created

**Comment by AntiD2ta** [comment]
[wiki][EN] Add sidebar

**Comment by AntiD2ta** [comment]
[wiki][EN] Add [setting up](https://github.com/2kodevs/matcom_scheduler/wiki/Setting-up) page.

**Comment by AntiD2ta** [comment]
[wiki][EN] Add [bot intro](https://github.com/2kodevs/matcom_scheduler/wiki/Introduction-to-the-bot) page

**Comment by AntiD2ta** [comment]
[wiki][EN] Add [start-help](https://github.com/2kodevs/matcom_scheduler/wiki/start-&-help) page

**Comment by e1Ru1o** [comment]
[wiki][EN] Add [config-handler](https://github.com/2kodevs/matcom_scheduler/wiki/Config-handler) page

**Comment by AntiD2ta** [comment]
[wiki][EN] Add [create and data management](https://github.com/2kodevs/matcom_scheduler/wiki/Create-&-Data-Management) page

**Comment by AntiD2ta** [comment]
[wiki][EN] Add [list, cancel and close](https://github.com/2kodevs/matcom_scheduler/wiki/List,-Cancel-and-Close-Handlers) page

**Comment by AntiD2ta** [comment]
[wiki][EN] Add [model](https://github.com/2kodevs/matcom_scheduler/wiki/Model) and [contact](https://github.com/2kodevs/matcom_scheduler/wiki/Contact) page
